### ISSUE TITLE
For ExoPlayer r2.11.x, monitoring ad playback via `com.google.android.exoplayer2.source.ads.AdsLoader` is not supported

### ISSUE THREAD

**Issue by jsanford8** [muxinc/mux-stats-sdk-exoplayer#40]
In r2.11.x of ExoPlayer, Google modified how ads are handled, at least in their demo applications. This version introduced the `com.google.android.exoplayer2.source.ads.AdsLoader` class, which does not expose the same information that is exposed directly by the Google IMA AdsLoader.

If you run ads as they do in the demo application on htttps://github.com/google/exoplayer, you will likely see rebuffering during playback of the ads.

We need to support monitoring ads when loaded via this mechanism.

**Comment by tomkordic** [comment]
This is covvered in card: https://zube.io/muxinc/mux/c/12185.

**Comment by jswapnil90** [comment]
@tomkordic @jsanford8 Is this bug resolved?
As per my observation, when MUX sdk is used with latest IMA and Exoplayer sdk, while video playback starts `rebufferStart` event is triggered as soon as ad starts playing and `rebufferEnd` is called when ad is ended. Which is leading to the huge increase in `Rebuffer Duration` after IMA ads integration in our apps.

Can you provide some alternate solution for this?

**Comment by tomkordic** [comment]
Hi Guys,

This bug is waiting for review, here is the PR:
https://github.com/muxinc/mux-stats-sdk-exoplayer/pull/41
Let me know if I can assist in any way.

Best regards,
Tom.

**Comment by Discovery-JSwapnil** [comment]
Thanks @tomkordic for updates.
Can you suggest some workaround from app side to avoid these unrelated events? It is misleading our video playback experience statistics largely. As because of this issue entire playback time of any ad, gets tracked as `Rebuffer Duration`.

When are we planning to merge these changes and release?

**Comment by jswapnil90** [comment]
Thanks @tomkordic for updates.

Because of this issue mentioned above, Mux is tracking ads playback duration as `Rebuffer Duration` which is misleading us for video playback experience validation. Any plans to merge this PR and release next version in coming days?

Can you suggest some workaround from app side with current SDK to avoid this unrelated events till then?
Thanks.

**Comment by tomkordic** [comment]
@jswapnil90
You could download the code from this branch and use it in your project,, that would be easiest, I will see if I can speed up the merge of this branch with master.

Here is the branch: https://github.com/muxinc/mux-stats-sdk-exoplayer/tree/r2_11_1

**Comment by jsanford8** [comment]
Hey @jswapnil90 - We are actively working on a release that will pull this in. I anticipate having it released next week.
